// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Stream

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenStream
void ui_ScreenStream_screen_init(void);
lv_obj_t * ui_ScreenStream;
lv_obj_t * ui_TVLabelHome;
lv_obj_t * ui_TVLabelReset;
lv_obj_t * ui_TVPanelPlayers;
lv_obj_t * ui_TVLabelPly1;
lv_obj_t * ui_TVLabelPly2;
lv_obj_t * ui_TVPanelGame;
lv_obj_t * ui_TVLabelGameScore1;
lv_obj_t * ui_TVLabelGameScore2;
lv_obj_t * ui_TVLabelGameScoreMax;
lv_obj_t * ui_TVPanelFrame;
lv_obj_t * ui_TVLabelFrameScore1;
lv_obj_t * ui_TVLabelFrameScoreReset;
lv_obj_t * ui_TVLabelFrameScore2;
lv_obj_t * ui_TVPanelGameReset;
lv_obj_t * ui_TVLabelGameResetQ;
lv_obj_t * ui_TVBtnGameResetYes;
lv_obj_t * ui_TVLabelGameResetYes;
lv_obj_t * ui_TVBtnGameResetNo;
lv_obj_t * ui_TVLabelGameResetNo;
lv_obj_t * ui_TVPanelFrameReset;
lv_obj_t * ui_TVLabelFrameResetQ;
lv_obj_t * ui_TVBtnFrameResetYes;
lv_obj_t * ui_TVLabelFrameResetYes;
lv_obj_t * ui_TVBtnFrameResetNo;
lv_obj_t * ui_TVLabelFrameResetNo;
lv_obj_t * ui_TVScoreKeyboard;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_snooker_table_480x[1] = {&ui_img_snooker_table_480x320_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenStream_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenStream);
}
