// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Stream

#ifndef _SQUARELINE_STREAM_UI_H
#define _SQUARELINE_STREAM_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_ScreenStream
void ui_ScreenStream_screen_init(void);
extern lv_obj_t * ui_ScreenStream;
extern lv_obj_t * ui_TVLabelHome;
extern lv_obj_t * ui_TVLabelReset;
extern lv_obj_t * ui_TVPanelPlayers;
extern lv_obj_t * ui_TVLabelPly1;
extern lv_obj_t * ui_TVLabelPly2;
extern lv_obj_t * ui_TVPanelGame;
extern lv_obj_t * ui_TVLabelGameScore1;
extern lv_obj_t * ui_TVLabelGameScore2;
extern lv_obj_t * ui_TVLabelGameScoreMax;
extern lv_obj_t * ui_TVPanelFrame;
extern lv_obj_t * ui_TVLabelFrameScore1;
extern lv_obj_t * ui_TVLabelFrameScoreReset;
extern lv_obj_t * ui_TVLabelFrameScore2;
extern lv_obj_t * ui_TVPanelGameReset;
extern lv_obj_t * ui_TVLabelGameResetQ;
extern lv_obj_t * ui_TVBtnGameResetYes;
extern lv_obj_t * ui_TVLabelGameResetYes;
extern lv_obj_t * ui_TVBtnGameResetNo;
extern lv_obj_t * ui_TVLabelGameResetNo;
extern lv_obj_t * ui_TVPanelFrameReset;
extern lv_obj_t * ui_TVLabelFrameResetQ;
extern lv_obj_t * ui_TVBtnFrameResetYes;
extern lv_obj_t * ui_TVLabelFrameResetYes;
extern lv_obj_t * ui_TVBtnFrameResetNo;
extern lv_obj_t * ui_TVLabelFrameResetNo;
extern lv_obj_t * ui_TVScoreKeyboard;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_snooker_table_480x320_png);    // assets/snooker_table_480x320.png



LV_FONT_DECLARE(ui_font_UbuntuCyrillic25);
LV_FONT_DECLARE(ui_font_UbuntuDigits92);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
