// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Main

#ifndef _SQUARELINE_MAIN_UI_H
#define _SQUARELINE_MAIN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_ScreenMain
void ui_ScreenMain_screen_init(void);
extern lv_obj_t * ui_ScreenMain;
extern lv_obj_t * ui_MLabelLogo;
extern lv_obj_t * ui_MBtnDarts;
extern lv_obj_t * ui_MBtnLabelDarts;
extern lv_obj_t * ui_MBtnLottery;
extern lv_obj_t * ui_MBtnLabelLottery;
extern lv_obj_t * ui_MBtnGame;
extern lv_obj_t * ui_MBtnLabelGame;
extern lv_obj_t * ui_MBtnStream;
extern lv_obj_t * ui_MBtnLabelStream;
extern lv_obj_t * ui_MBtnSnooker;
extern lv_obj_t * ui_MBtnLabelSnooker;
extern lv_obj_t * ui_MBtnSettings;
extern lv_obj_t * ui_MBtnLabelSettings;
extern lv_obj_t * ui_MLabelWifi;
extern lv_obj_t * ui_MLabelTelega;
extern lv_obj_t * ui_MLabelAudio;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_snooker_table_480x320_png);    // assets/snooker_table_480x320.png



LV_FONT_DECLARE(ui_font_UbuntuCyrillic25);
LV_FONT_DECLARE(ui_font_UbuntuDigits92);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
