// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Game

#include "../ui.h"

void ui_ScreenGame_screen_init(void)
{
    ui_ScreenGame = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenGame, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ScreenGame, &ui_img_snooker_table_480x320_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ScreenGame, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ScreenGame, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScreenGame, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScreenGame, &ui_font_UbuntuCyrillic25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GLabelHome = lv_label_create(ui_ScreenGame);
    lv_obj_set_width(ui_GLabelHome, 110);
    lv_obj_set_height(ui_GLabelHome, 50);
    lv_obj_set_x(ui_GLabelHome, -160);
    lv_obj_set_y(ui_GLabelHome, 125);
    lv_obj_set_align(ui_GLabelHome, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GLabelHome, "# Назад");
    lv_obj_add_flag(ui_GLabelHome, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_align(ui_GLabelHome, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GLabelRefresh = lv_label_create(ui_ScreenGame);
    lv_obj_set_width(ui_GLabelRefresh, 145);
    lv_obj_set_height(ui_GLabelRefresh, 50);
    lv_obj_set_x(ui_GLabelRefresh, 140);
    lv_obj_set_y(ui_GLabelRefresh, 125);
    lv_obj_set_align(ui_GLabelRefresh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GLabelRefresh, "Новый #");
    lv_obj_add_flag(ui_GLabelRefresh, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_align(ui_GLabelRefresh, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GSwitchPlyCount = lv_switch_create(ui_ScreenGame);
    lv_obj_set_width(ui_GSwitchPlyCount, 64);
    lv_obj_set_height(ui_GSwitchPlyCount, 32);
    lv_obj_set_x(ui_GSwitchPlyCount, 0);
    lv_obj_set_y(ui_GSwitchPlyCount, 115);
    lv_obj_set_align(ui_GSwitchPlyCount, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_GSwitchPlyCount, lv_color_hex(0x836529), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GSwitchPlyCount, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GSwitchPlyCount, lv_color_hex(0x004C00), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_GSwitchPlyCount, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_GSwitchPlyCount, lv_color_hex(0x004C00), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GSwitchPlyCount, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GSwitchPlyCount, lv_color_hex(0x836529), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_GSwitchPlyCount, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_GLabel2 = lv_label_create(ui_ScreenGame);
    lv_obj_set_width(ui_GLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GLabel2, -45);
    lv_obj_set_y(ui_GLabel2, 115);
    lv_obj_set_align(ui_GLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GLabel2, "2");

    ui_GLabel3 = lv_label_create(ui_ScreenGame);
    lv_obj_set_width(ui_GLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GLabel3, 45);
    lv_obj_set_y(ui_GLabel3, 115);
    lv_obj_set_align(ui_GLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GLabel3, "3");

    ui_GPanelPool2 = lv_obj_create(ui_ScreenGame);
    lv_obj_set_width(ui_GPanelPool2, 430);
    lv_obj_set_height(ui_GPanelPool2, 225);
    lv_obj_set_x(ui_GPanelPool2, 0);
    lv_obj_set_y(ui_GPanelPool2, 30);
    lv_obj_set_align(ui_GPanelPool2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_GPanelPool2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GPanelPool2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GPanelPool2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_GPanelPool2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPool2Ply1 = ui_PanelPoolPlayer_create(ui_GPanelPool2);
    lv_obj_set_x(ui_PanelPool2Ply1, -125);
    lv_obj_set_y(ui_PanelPool2Ply1, 0);



    lv_label_set_text(ui_comp_get_child(ui_PanelPool2Ply1, UI_COMP_PANELPOOLPLAYER_LABELPOOLPLYNAME), "Игрок 1");



    ui_GImageBreak0 = lv_img_create(ui_GPanelPool2);
    lv_img_set_src(ui_GImageBreak0, &ui_img_break0_png);
    lv_obj_set_width(ui_GImageBreak0, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_GImageBreak0, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_align(ui_GImageBreak0, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GImageBreak0, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_GImageBreak0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GImageBreak180 = lv_img_create(ui_GPanelPool2);
    lv_img_set_src(ui_GImageBreak180, &ui_img_break180_png);
    lv_obj_set_width(ui_GImageBreak180, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_GImageBreak180, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_align(ui_GImageBreak180, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GImageBreak180, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_GImageBreak180, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelPool2Ply2 = ui_PanelPoolPlayer_create(ui_GPanelPool2);
    lv_obj_set_x(ui_PanelPool2Ply2, 125);
    lv_obj_set_y(ui_PanelPool2Ply2, 0);



    lv_label_set_text(ui_comp_get_child(ui_PanelPool2Ply2, UI_COMP_PANELPOOLPLAYER_LABELPOOLPLYNAME), "Игрок 2");



    ui_GPanelPool3 = lv_obj_create(ui_ScreenGame);
    lv_obj_set_width(ui_GPanelPool3, 430);
    lv_obj_set_height(ui_GPanelPool3, 225);
    lv_obj_set_x(ui_GPanelPool3, 0);
    lv_obj_set_y(ui_GPanelPool3, 30);
    lv_obj_set_align(ui_GPanelPool3, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_GPanelPool3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_GPanelPool3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GPanelPool3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GPanelPool3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_GPanelPool3, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPool3Ply1 = ui_PanelPoolPlayer_create(ui_GPanelPool3);
    lv_obj_set_width(ui_PanelPool3Ply1, 140);
    lv_obj_set_height(ui_PanelPool3Ply1, 220);
    lv_obj_set_x(ui_PanelPool3Ply1, -145);
    lv_obj_set_y(ui_PanelPool3Ply1, 0);



    lv_label_set_text(ui_comp_get_child(ui_PanelPool3Ply1, UI_COMP_PANELPOOLPLAYER_LABELPOOLPLYNAME), "Игрок 1");



    ui_PanelPool3Ply2 = ui_PanelPoolPlayer_create(ui_GPanelPool3);
    lv_obj_set_width(ui_PanelPool3Ply2, 140);
    lv_obj_set_height(ui_PanelPool3Ply2, 220);
    lv_obj_set_x(ui_PanelPool3Ply2, 0);
    lv_obj_set_y(ui_PanelPool3Ply2, 0);



    lv_label_set_text(ui_comp_get_child(ui_PanelPool3Ply2, UI_COMP_PANELPOOLPLAYER_LABELPOOLPLYNAME), "Игрок 2");



    ui_PanelPool3Ply3 = ui_PanelPoolPlayer_create(ui_GPanelPool3);
    lv_obj_set_width(ui_PanelPool3Ply3, 140);
    lv_obj_set_height(ui_PanelPool3Ply3, 220);
    lv_obj_set_x(ui_PanelPool3Ply3, 145);
    lv_obj_set_y(ui_PanelPool3Ply3, 0);



    lv_label_set_text(ui_comp_get_child(ui_PanelPool3Ply3, UI_COMP_PANELPOOLPLAYER_LABELPOOLPLYNAME), "Игрок 3");



    ui_MBPanelPool = lv_obj_create(ui_ScreenGame);
    lv_obj_set_width(ui_MBPanelPool, 430);
    lv_obj_set_height(ui_MBPanelPool, 225);
    lv_obj_set_x(ui_MBPanelPool, 0);
    lv_obj_set_y(ui_MBPanelPool, 30);
    lv_obj_set_align(ui_MBPanelPool, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_MBPanelPool, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_MBPanelPool, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MBPanelPool, lv_color_hex(0x157207), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MBPanelPool, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MBPanelPool, lv_color_hex(0x6A5529), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MBPanelPool, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MBLabelPoolResetQ = lv_label_create(ui_MBPanelPool);
    lv_obj_set_width(ui_MBLabelPoolResetQ, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MBLabelPoolResetQ, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MBLabelPoolResetQ, 0);
    lv_obj_set_y(ui_MBLabelPoolResetQ, 35);
    lv_obj_set_align(ui_MBLabelPoolResetQ, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_MBLabelPoolResetQ, "Начать новый матч?");
    lv_obj_set_style_text_color(ui_MBLabelPoolResetQ, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MBLabelPoolResetQ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MBBtnPoolResetYes = lv_btn_create(ui_MBPanelPool);
    lv_obj_set_width(ui_MBBtnPoolResetYes, 165);
    lv_obj_set_height(ui_MBBtnPoolResetYes, 65);
    lv_obj_set_x(ui_MBBtnPoolResetYes, -110);
    lv_obj_set_y(ui_MBBtnPoolResetYes, 60);
    lv_obj_set_align(ui_MBBtnPoolResetYes, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MBBtnPoolResetYes, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MBBtnPoolResetYes, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MBBtnPoolResetYes, lv_color_hex(0x1E3E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MBBtnPoolResetYes, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_MBBtnPoolResetYes, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MBLabelPoolResetYes = lv_label_create(ui_MBBtnPoolResetYes);
    lv_obj_set_width(ui_MBLabelPoolResetYes, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MBLabelPoolResetYes, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MBLabelPoolResetYes, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MBLabelPoolResetYes, "ДА");

    ui_MBBtnPoolResetNo = lv_btn_create(ui_MBPanelPool);
    lv_obj_set_width(ui_MBBtnPoolResetNo, 165);
    lv_obj_set_height(ui_MBBtnPoolResetNo, 65);
    lv_obj_set_x(ui_MBBtnPoolResetNo, 110);
    lv_obj_set_y(ui_MBBtnPoolResetNo, 60);
    lv_obj_set_align(ui_MBBtnPoolResetNo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MBBtnPoolResetNo, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MBBtnPoolResetNo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MBBtnPoolResetNo, lv_color_hex(0x183C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MBBtnPoolResetNo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_MBBtnPoolResetNo, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MBLabelPoolResetNo = lv_label_create(ui_MBBtnPoolResetNo);
    lv_obj_set_width(ui_MBLabelPoolResetNo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MBLabelPoolResetNo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MBLabelPoolResetNo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MBLabelPoolResetNo, "НЕТ");

}
