// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Darts

#include "../ui.h"


void ui_event_comp_NameKeyboard_NameKeyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    lv_obj_t ** comp_NameKeyboard = lv_event_get_user_data(e);
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(comp_NameKeyboard[UI_COMP_NAMEKEYBOARD_NAMEKEYBOARD], LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// COMPONENT NameKeyboard

lv_obj_t * ui_NameKeyboard_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_NameKeyboard;
    cui_NameKeyboard = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_NameKeyboard, lv_pct(100));
    lv_obj_set_height(cui_NameKeyboard, lv_pct(100));
    lv_obj_set_align(cui_NameKeyboard, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_NameKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(cui_NameKeyboard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_NameKeyboard, lv_color_hex(0x105508), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_NameKeyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_NameKeyboard, &ui_font_UbuntuCyrillic25, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_NameList;
    cui_NameList = lv_dropdown_create(cui_NameKeyboard);
    lv_dropdown_set_options(cui_NameList,
                            "Дима\nПаша\nИгорь\nСергей\nВова\nВиталик\nСаша\nДенис");
    lv_dropdown_set_text(cui_NameList, "Выбрать");
    lv_obj_set_width(cui_NameList, 150);
    lv_obj_set_height(cui_NameList, LV_SIZE_CONTENT);    /// 1
    lv_obj_add_flag(cui_NameList, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_t * cui_NameTextArea;
    cui_NameTextArea = lv_textarea_create(cui_NameKeyboard);
    lv_obj_set_width(cui_NameTextArea, 230);
    lv_obj_set_height(cui_NameTextArea, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_NameTextArea, 160);
    lv_obj_set_y(cui_NameTextArea, 0);
    lv_obj_set_align(cui_NameTextArea, LV_ALIGN_TOP_RIGHT);
    lv_textarea_set_max_length(cui_NameTextArea, 95);
    lv_textarea_set_placeholder_text(cui_NameTextArea, "Имя...");
    lv_textarea_set_one_line(cui_NameTextArea, true);

    lv_obj_t * cui_ButtonClose;
    cui_ButtonClose = lv_btn_create(cui_NameKeyboard);
    lv_obj_set_height(cui_ButtonClose, 53);
    lv_obj_set_width(cui_ButtonClose, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(cui_ButtonClose, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(cui_ButtonClose, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_ButtonClose, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_ButtonClose, lv_color_hex(0x6A5529), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_ButtonClose, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_LabelClose;
    cui_LabelClose = lv_label_create(cui_ButtonClose);
    lv_obj_set_width(cui_LabelClose, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LabelClose, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_LabelClose, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LabelClose, "#LV_SYMBOL_CLOSE#");
    lv_label_set_recolor(cui_LabelClose, "true");

    lv_obj_t * cui_KeyboardButtons;
    cui_KeyboardButtons = lv_keyboard_create(cui_NameKeyboard);
    lv_keyboard_set_mode(cui_KeyboardButtons, LV_KEYBOARD_MODE_TEXT_UPPER);
    lv_obj_set_width(cui_KeyboardButtons, lv_pct(100));
    lv_obj_set_height(cui_KeyboardButtons, lv_pct(75));
    lv_obj_set_align(cui_KeyboardButtons, LV_ALIGN_BOTTOM_MID);

    lv_obj_set_style_text_font(cui_KeyboardButtons, &ui_font_UbuntuCyrillic25, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_NAMEKEYBOARD_NUM);
    children[UI_COMP_NAMEKEYBOARD_NAMEKEYBOARD] = cui_NameKeyboard;
    children[UI_COMP_NAMEKEYBOARD_NAMELIST] = cui_NameList;
    children[UI_COMP_NAMEKEYBOARD_NAMETEXTAREA] = cui_NameTextArea;
    children[UI_COMP_NAMEKEYBOARD_BUTTONCLOSE] = cui_ButtonClose;
    children[UI_COMP_NAMEKEYBOARD_BUTTONCLOSE_LABELCLOSE] = cui_LabelClose;
    children[UI_COMP_NAMEKEYBOARD_KEYBOARDBUTTONS] = cui_KeyboardButtons;
    lv_obj_add_event_cb(cui_NameKeyboard, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_NameKeyboard, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_NameKeyboard, ui_event_comp_NameKeyboard_NameKeyboard, LV_EVENT_ALL, children);
    ui_comp_NameKeyboard_create_hook(cui_NameKeyboard);
    return cui_NameKeyboard;
}

