// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Stream

#include "../ui.h"

void ui_ScreenStream_screen_init(void)
{
    ui_ScreenStream = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenStream, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ScreenStream, &ui_img_snooker_table_480x320_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ScreenStream, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ScreenStream, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScreenStream, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScreenStream, &ui_font_UbuntuCyrillic25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TVLabelHome = lv_label_create(ui_ScreenStream);
    lv_obj_set_width(ui_TVLabelHome, 110);
    lv_obj_set_height(ui_TVLabelHome, 50);
    lv_obj_set_x(ui_TVLabelHome, -160);
    lv_obj_set_y(ui_TVLabelHome, 125);
    lv_obj_set_align(ui_TVLabelHome, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TVLabelHome, "# Назад");
    lv_obj_add_flag(ui_TVLabelHome, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_align(ui_TVLabelHome, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TVLabelReset = lv_label_create(ui_ScreenStream);
    lv_obj_set_width(ui_TVLabelReset, 180);
    lv_obj_set_height(ui_TVLabelReset, 50);
    lv_obj_set_x(ui_TVLabelReset, 120);
    lv_obj_set_y(ui_TVLabelReset, 125);
    lv_obj_set_align(ui_TVLabelReset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TVLabelReset, "Новый матч #");
    lv_obj_add_flag(ui_TVLabelReset, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_align(ui_TVLabelReset, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TVPanelPlayers = lv_obj_create(ui_ScreenStream);
    lv_obj_set_width(ui_TVPanelPlayers, 420);
    lv_obj_set_height(ui_TVPanelPlayers, 50);
    lv_obj_set_x(ui_TVPanelPlayers, 0);
    lv_obj_set_y(ui_TVPanelPlayers, 35);
    lv_obj_set_align(ui_TVPanelPlayers, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_TVPanelPlayers, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TVPanelPlayers, lv_color_hex(0x1E5016), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TVPanelPlayers, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TVPanelPlayers, lv_color_hex(0x6A5529), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TVPanelPlayers, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_TVPanelPlayers, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TVPanelPlayers, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TVPanelPlayers, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TVLabelPly1 = lv_label_create(ui_TVPanelPlayers);
    lv_obj_set_width(ui_TVLabelPly1, lv_pct(45));
    lv_obj_set_height(ui_TVLabelPly1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TVLabelPly1, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_TVLabelPly1, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_TVLabelPly1, "Игрок 1");
    lv_obj_add_flag(ui_TVLabelPly1, LV_OBJ_FLAG_CLICKABLE);     /// Flags

    ui_TVLabelPly2 = lv_label_create(ui_TVPanelPlayers);
    lv_obj_set_width(ui_TVLabelPly2, lv_pct(45));
    lv_obj_set_height(ui_TVLabelPly2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TVLabelPly2, LV_ALIGN_RIGHT_MID);
    lv_label_set_long_mode(ui_TVLabelPly2, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_TVLabelPly2, "Игрок 2");
    lv_obj_add_flag(ui_TVLabelPly2, LV_OBJ_FLAG_CLICKABLE);     /// Flags

    ui_TVPanelGame = lv_obj_create(ui_ScreenStream);
    lv_obj_set_width(ui_TVPanelGame, 420);
    lv_obj_set_height(ui_TVPanelGame, 60);
    lv_obj_set_x(ui_TVPanelGame, 0);
    lv_obj_set_y(ui_TVPanelGame, -65);
    lv_obj_set_align(ui_TVPanelGame, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_TVPanelGame, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TVPanelGame, lv_color_hex(0x1E5016), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TVPanelGame, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TVPanelGame, lv_color_hex(0x6A5529), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TVPanelGame, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_TVPanelGame, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TVPanelGame, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TVPanelGame, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TVPanelGame, &ui_font_UbuntuCyrillic25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TVLabelGameScore1 = lv_label_create(ui_TVPanelGame);
    lv_obj_set_width(ui_TVLabelGameScore1, lv_pct(40));
    lv_obj_set_height(ui_TVLabelGameScore1, LV_SIZE_CONTENT);    /// 90
    lv_obj_set_x(ui_TVLabelGameScore1, -10);
    lv_obj_set_y(ui_TVLabelGameScore1, 0);
    lv_obj_set_align(ui_TVLabelGameScore1, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_TVLabelGameScore1, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_TVLabelGameScore1, "999");
    lv_obj_add_flag(ui_TVLabelGameScore1, LV_OBJ_FLAG_CLICKABLE);     /// Flags

    ui_TVLabelGameScore2 = lv_label_create(ui_TVPanelGame);
    lv_obj_set_width(ui_TVLabelGameScore2, lv_pct(40));
    lv_obj_set_height(ui_TVLabelGameScore2, LV_SIZE_CONTENT);    /// 90
    lv_obj_set_x(ui_TVLabelGameScore2, 10);
    lv_obj_set_y(ui_TVLabelGameScore2, 0);
    lv_obj_set_align(ui_TVLabelGameScore2, LV_ALIGN_RIGHT_MID);
    lv_label_set_long_mode(ui_TVLabelGameScore2, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_TVLabelGameScore2, "-100");
    lv_obj_add_flag(ui_TVLabelGameScore2, LV_OBJ_FLAG_CLICKABLE);     /// Flags

    ui_TVLabelGameScoreMax = lv_label_create(ui_TVPanelGame);
    lv_obj_set_width(ui_TVLabelGameScoreMax, lv_pct(20));
    lv_obj_set_height(ui_TVLabelGameScoreMax, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_TVLabelGameScoreMax, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_TVLabelGameScoreMax, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_TVLabelGameScoreMax, "(150)");
    lv_obj_add_flag(ui_TVLabelGameScoreMax, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_TVLabelGameScoreMax, lv_color_hex(0xBDBABA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TVLabelGameScoreMax, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TVLabelGameScoreMax, &ui_font_UbuntuCyrillic25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TVPanelFrame = lv_obj_create(ui_ScreenStream);
    lv_obj_set_width(ui_TVPanelFrame, 420);
    lv_obj_set_height(ui_TVPanelFrame, LV_SIZE_CONTENT);    /// 60
    lv_obj_set_x(ui_TVPanelFrame, 0);
    lv_obj_set_y(ui_TVPanelFrame, -20);
    lv_obj_set_align(ui_TVPanelFrame, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TVPanelFrame, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TVPanelFrame, lv_color_hex(0x1E5016), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TVPanelFrame, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TVPanelFrame, lv_color_hex(0x6A5529), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TVPanelFrame, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_TVPanelFrame, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TVPanelFrame, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TVPanelFrame, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TVPanelFrame, &ui_font_UbuntuDigits92, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TVLabelFrameScore1 = lv_label_create(ui_TVPanelFrame);
    lv_obj_set_width(ui_TVLabelFrameScore1, lv_pct(45));
    lv_obj_set_height(ui_TVLabelFrameScore1, LV_SIZE_CONTENT);    /// 90
    lv_obj_set_align(ui_TVLabelFrameScore1, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_TVLabelFrameScore1, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_TVLabelFrameScore1, "-147");
    lv_obj_add_flag(ui_TVLabelFrameScore1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_align(ui_TVLabelFrameScore1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TVLabelFrameScoreReset = lv_label_create(ui_TVPanelFrame);
    lv_obj_set_width(ui_TVLabelFrameScoreReset, 40);
    lv_obj_set_height(ui_TVLabelFrameScoreReset, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_align(ui_TVLabelFrameScoreReset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TVLabelFrameScoreReset, "#");
    lv_obj_add_flag(ui_TVLabelFrameScoreReset, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_TVLabelFrameScoreReset, &ui_font_UbuntuCyrillic25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TVLabelFrameScore2 = lv_label_create(ui_TVPanelFrame);
    lv_obj_set_width(ui_TVLabelFrameScore2, lv_pct(45));
    lv_obj_set_height(ui_TVLabelFrameScore2, LV_SIZE_CONTENT);    /// 90
    lv_obj_set_align(ui_TVLabelFrameScore2, LV_ALIGN_RIGHT_MID);
    lv_label_set_long_mode(ui_TVLabelFrameScore2, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_TVLabelFrameScore2, "147");
    lv_obj_add_flag(ui_TVLabelFrameScore2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_align(ui_TVLabelFrameScore2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TVPanelGameReset = lv_obj_create(ui_ScreenStream);
    lv_obj_set_width(ui_TVPanelGameReset, 430);
    lv_obj_set_height(ui_TVPanelGameReset, 225);
    lv_obj_set_x(ui_TVPanelGameReset, 0);
    lv_obj_set_y(ui_TVPanelGameReset, 30);
    lv_obj_set_align(ui_TVPanelGameReset, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_TVPanelGameReset, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_TVPanelGameReset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TVPanelGameReset, lv_color_hex(0x157207), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TVPanelGameReset, 235, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TVPanelGameReset, lv_color_hex(0x6A5529), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TVPanelGameReset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TVLabelGameResetQ = lv_label_create(ui_TVPanelGameReset);
    lv_obj_set_width(ui_TVLabelGameResetQ, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TVLabelGameResetQ, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TVLabelGameResetQ, 0);
    lv_obj_set_y(ui_TVLabelGameResetQ, 35);
    lv_obj_set_align(ui_TVLabelGameResetQ, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_TVLabelGameResetQ, "Начать новый матч?");
    lv_obj_set_style_text_color(ui_TVLabelGameResetQ, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TVLabelGameResetQ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TVBtnGameResetYes = lv_btn_create(ui_TVPanelGameReset);
    lv_obj_set_width(ui_TVBtnGameResetYes, 165);
    lv_obj_set_height(ui_TVBtnGameResetYes, 65);
    lv_obj_set_x(ui_TVBtnGameResetYes, -110);
    lv_obj_set_y(ui_TVBtnGameResetYes, 60);
    lv_obj_set_align(ui_TVBtnGameResetYes, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TVBtnGameResetYes, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TVBtnGameResetYes, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TVBtnGameResetYes, lv_color_hex(0x1E3E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TVBtnGameResetYes, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TVBtnGameResetYes, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TVLabelGameResetYes = lv_label_create(ui_TVBtnGameResetYes);
    lv_obj_set_width(ui_TVLabelGameResetYes, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TVLabelGameResetYes, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TVLabelGameResetYes, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TVLabelGameResetYes, "ДА");

    ui_TVBtnGameResetNo = lv_btn_create(ui_TVPanelGameReset);
    lv_obj_set_width(ui_TVBtnGameResetNo, 165);
    lv_obj_set_height(ui_TVBtnGameResetNo, 65);
    lv_obj_set_x(ui_TVBtnGameResetNo, 110);
    lv_obj_set_y(ui_TVBtnGameResetNo, 60);
    lv_obj_set_align(ui_TVBtnGameResetNo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TVBtnGameResetNo, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TVBtnGameResetNo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TVBtnGameResetNo, lv_color_hex(0x183C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TVBtnGameResetNo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TVBtnGameResetNo, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TVLabelGameResetNo = lv_label_create(ui_TVBtnGameResetNo);
    lv_obj_set_width(ui_TVLabelGameResetNo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TVLabelGameResetNo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TVLabelGameResetNo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TVLabelGameResetNo, "НЕТ");

    ui_TVPanelFrameReset = lv_obj_create(ui_ScreenStream);
    lv_obj_set_width(ui_TVPanelFrameReset, 430);
    lv_obj_set_height(ui_TVPanelFrameReset, 225);
    lv_obj_set_x(ui_TVPanelFrameReset, 0);
    lv_obj_set_y(ui_TVPanelFrameReset, 30);
    lv_obj_set_align(ui_TVPanelFrameReset, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_TVPanelFrameReset, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_TVPanelFrameReset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TVPanelFrameReset, lv_color_hex(0x157207), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TVPanelFrameReset, 235, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TVPanelFrameReset, lv_color_hex(0x6A5529), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TVPanelFrameReset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TVLabelFrameResetQ = lv_label_create(ui_TVPanelFrameReset);
    lv_obj_set_width(ui_TVLabelFrameResetQ, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TVLabelFrameResetQ, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TVLabelFrameResetQ, 0);
    lv_obj_set_y(ui_TVLabelFrameResetQ, 35);
    lv_obj_set_align(ui_TVLabelFrameResetQ, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_TVLabelFrameResetQ, "Сбросить счёт в партии?");
    lv_obj_set_style_text_color(ui_TVLabelFrameResetQ, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TVLabelFrameResetQ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TVBtnFrameResetYes = lv_btn_create(ui_TVPanelFrameReset);
    lv_obj_set_width(ui_TVBtnFrameResetYes, 165);
    lv_obj_set_height(ui_TVBtnFrameResetYes, 65);
    lv_obj_set_x(ui_TVBtnFrameResetYes, -110);
    lv_obj_set_y(ui_TVBtnFrameResetYes, 60);
    lv_obj_set_align(ui_TVBtnFrameResetYes, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TVBtnFrameResetYes, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TVBtnFrameResetYes, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TVBtnFrameResetYes, lv_color_hex(0x1E3E02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TVBtnFrameResetYes, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TVBtnFrameResetYes, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TVLabelFrameResetYes = lv_label_create(ui_TVBtnFrameResetYes);
    lv_obj_set_width(ui_TVLabelFrameResetYes, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TVLabelFrameResetYes, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TVLabelFrameResetYes, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TVLabelFrameResetYes, "ДА");

    ui_TVBtnFrameResetNo = lv_btn_create(ui_TVPanelFrameReset);
    lv_obj_set_width(ui_TVBtnFrameResetNo, 165);
    lv_obj_set_height(ui_TVBtnFrameResetNo, 65);
    lv_obj_set_x(ui_TVBtnFrameResetNo, 110);
    lv_obj_set_y(ui_TVBtnFrameResetNo, 60);
    lv_obj_set_align(ui_TVBtnFrameResetNo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TVBtnFrameResetNo, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TVBtnFrameResetNo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TVBtnFrameResetNo, lv_color_hex(0x183C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TVBtnFrameResetNo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TVBtnFrameResetNo, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TVLabelFrameResetNo = lv_label_create(ui_TVBtnFrameResetNo);
    lv_obj_set_width(ui_TVLabelFrameResetNo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TVLabelFrameResetNo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TVLabelFrameResetNo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TVLabelFrameResetNo, "НЕТ");

    ui_TVScoreKeyboard = ui_ScoreKeyboard_create(ui_ScreenStream);
    lv_obj_set_x(ui_TVScoreKeyboard, 0);
    lv_obj_set_y(ui_TVScoreKeyboard, 0);







}
