// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Game

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenGame
void ui_ScreenGame_screen_init(void);
lv_obj_t * ui_ScreenGame;
lv_obj_t * ui_GLabelHome;
lv_obj_t * ui_GLabelRefresh;
lv_obj_t * ui_GSwitchPlyCount;
lv_obj_t * ui_GLabel2;
lv_obj_t * ui_GLabel3;
lv_obj_t * ui_GPanelPool2;
lv_obj_t * ui_PanelPool2Ply1;
lv_obj_t * ui_GImageBreak0;
lv_obj_t * ui_GImageBreak180;
lv_obj_t * ui_PanelPool2Ply2;
lv_obj_t * ui_GPanelPool3;
lv_obj_t * ui_PanelPool3Ply1;
lv_obj_t * ui_PanelPool3Ply2;
lv_obj_t * ui_PanelPool3Ply3;
lv_obj_t * ui_MBPanelPool;
lv_obj_t * ui_MBLabelPoolResetQ;
lv_obj_t * ui_MBBtnPoolResetYes;
lv_obj_t * ui_MBLabelPoolResetYes;
lv_obj_t * ui_MBBtnPoolResetNo;
lv_obj_t * ui_MBLabelPoolResetNo;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_break[2] = {&ui_img_break0_png, &ui_img_break180_png};
const lv_img_dsc_t * ui_imgset_snooker_table_480x[1] = {&ui_img_snooker_table_480x320_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenGame_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenGame);
}
