// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Game

#ifndef _SQUARELINE_GAME_UI_H
#define _SQUARELINE_GAME_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_ScreenGame
void ui_ScreenGame_screen_init(void);
extern lv_obj_t * ui_ScreenGame;
extern lv_obj_t * ui_GLabelHome;
extern lv_obj_t * ui_GLabelRefresh;
extern lv_obj_t * ui_GSwitchPlyCount;
extern lv_obj_t * ui_GLabel2;
extern lv_obj_t * ui_GLabel3;
extern lv_obj_t * ui_GPanelPool2;
extern lv_obj_t * ui_PanelPool2Ply1;
extern lv_obj_t * ui_GImageBreak0;
extern lv_obj_t * ui_GImageBreak180;
extern lv_obj_t * ui_PanelPool2Ply2;
extern lv_obj_t * ui_GPanelPool3;
extern lv_obj_t * ui_PanelPool3Ply1;
extern lv_obj_t * ui_PanelPool3Ply2;
extern lv_obj_t * ui_PanelPool3Ply3;
extern lv_obj_t * ui_MBPanelPool;
extern lv_obj_t * ui_MBLabelPoolResetQ;
extern lv_obj_t * ui_MBBtnPoolResetYes;
extern lv_obj_t * ui_MBLabelPoolResetYes;
extern lv_obj_t * ui_MBBtnPoolResetNo;
extern lv_obj_t * ui_MBLabelPoolResetNo;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_snooker_table_480x320_png);    // assets/snooker_table_480x320.png
LV_IMG_DECLARE(ui_img_break0_png);    // assets/break0.png
LV_IMG_DECLARE(ui_img_break180_png);    // assets/break180.png



LV_FONT_DECLARE(ui_font_UbuntuCyrillic25);
LV_FONT_DECLARE(ui_font_UbuntuDigits92);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
