// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Game

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void changeScore(lv_event_t * e);
void changeScorePlus(lv_event_t * e);
void changeScoreMinus(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
