// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Settings

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenSettings
void ui_ScreenSettings_screen_init(void);
lv_obj_t * ui_ScreenSettings;
lv_obj_t * ui_SLabelHome;
lv_obj_t * ui_SPanelSettings;
void ui_event_SButtonRestore(lv_event_t * e);
lv_obj_t * ui_SButtonRestore;
lv_obj_t * ui_SLabelRestore;
lv_obj_t * ui_SPanelGeneral;
lv_obj_t * ui_SLabelWifi;
lv_obj_t * ui_SSwitchWifi;
lv_obj_t * ui_SLabelTelega;
lv_obj_t * ui_SSwitchTelega;
lv_obj_t * ui_SLabelAudio;
lv_obj_t * ui_SSwitchAudio;
lv_obj_t * ui_SLabelVolume;
lv_obj_t * ui_SSliderVolume;
lv_obj_t * ui_SLabelAP;
lv_obj_t * ui_SSwitchAP;
lv_obj_t * ui_SPanelSnooker;
lv_obj_t * ui_SLabelSnooker;
lv_obj_t * ui_SLabel6Red;
lv_obj_t * ui_SSwitch6Red;
lv_obj_t * ui_SLabelControlBalls;
lv_obj_t * ui_SSwitchControlBalls;
lv_obj_t * ui_SLabekHandicap1;
lv_obj_t * ui_SLabekHandicapValue1;
lv_obj_t * ui_SButtonEditHandicap1;
lv_obj_t * ui_SLabelEditHandicap1;
lv_obj_t * ui_SLabekHandicap2;
lv_obj_t * ui_SLabekHandicapValue2;
lv_obj_t * ui_SButtonEditHandicap2;
lv_obj_t * ui_SLabelEditHandicap2;
lv_obj_t * ui_SPanelOptions;
lv_obj_t * ui_SLabelOptions;
lv_obj_t * ui_SPanelOptions1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_SButtonEditGreeting;
lv_obj_t * ui_SLabelEditGreeting;
lv_obj_t * ui_SPanelOptions2;
lv_obj_t * ui_Label2;
lv_obj_t * ui_SButtonEditSSID;
lv_obj_t * ui_SLabelEditSSID;
lv_obj_t * ui_SPanelOptions3;
lv_obj_t * ui_Label3;
lv_obj_t * ui_SButtonEditWifiPass;
lv_obj_t * ui_SLabelEditWifiPass;
lv_obj_t * ui_SPanelOptions4;
lv_obj_t * ui_Label4;
lv_obj_t * ui_SButtonEditTelegaChannel;
lv_obj_t * ui_SLabelEditTelegaChannel;
lv_obj_t * ui_SPanelOptions5;
lv_obj_t * ui_Label5;
lv_obj_t * ui_SButtonEditMqttHost;
lv_obj_t * ui_SLabelEditMqttHost;
lv_obj_t * ui_SPanelOptions6;
lv_obj_t * ui_Label6;
lv_obj_t * ui_SButtonEditMqttPort;
lv_obj_t * ui_SLabelEditMqttPort;
lv_obj_t * ui_SPanelOptions7;
lv_obj_t * ui_Label7;
lv_obj_t * ui_SButtonEditMqttUser;
lv_obj_t * ui_SLabelEditMqttUser;
lv_obj_t * ui_SPanelOptions8;
lv_obj_t * ui_Label8;
lv_obj_t * ui_SButtonEditMqttPass;
lv_obj_t * ui_SLabelEditMqttPass;
lv_obj_t * ui_SButtonSaveAll;
lv_obj_t * ui_SLabelSaveAll;
lv_obj_t * ui_SOptionKeyboard;


// SCREEN: ui_ScreenRestore
void ui_ScreenRestore_screen_init(void);
lv_obj_t * ui_ScreenRestore;
lv_obj_t * ui_RLabelQuestion;
lv_obj_t * ui_RLabelWait;
void ui_event_RButtonYes(lv_event_t * e);
lv_obj_t * ui_RButtonYes;
lv_obj_t * ui_RLabelYes;
void ui_event_RButtonCancel(lv_event_t * e);
lv_obj_t * ui_RButtonCancel;
lv_obj_t * ui_RLabelCancel;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_snooker_table_480x[1] = {&ui_img_snooker_table_480x320_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_SButtonRestore(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenRestore, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_ScreenRestore_screen_init);
    }
}
void ui_event_RButtonYes(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_RButtonYes, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_RButtonCancel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenSettings, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_ScreenSettings_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenSettings_screen_init();
    ui_ScreenRestore_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenSettings);
}
