// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Settings

#ifndef _UI_COMP_OPTIONSKEYBOARD_H
#define _UI_COMP_OPTIONSKEYBOARD_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT OptionsKeyboard
#define UI_COMP_OPTIONSKEYBOARD_OPTIONSKEYBOARD 0
#define UI_COMP_OPTIONSKEYBOARD_OPTIONTEXTAREA 1
#define UI_COMP_OPTIONSKEYBOARD_BUTTONCLOSE 2
#define UI_COMP_OPTIONSKEYBOARD_BUTTONCLOSE_LABELCLOSE 3
#define UI_COMP_OPTIONSKEYBOARD_KEYBOARDBUTTONS 4
#define _UI_COMP_OPTIONSKEYBOARD_NUM 5
lv_obj_t * ui_OptionsKeyboard_create(lv_obj_t * comp_parent);
void ui_event_comp_OptionsKeyboard_OptionsKeyboard(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
