// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Game

#ifndef _UI_COMP_PANELPOOLPLAYER_H
#define _UI_COMP_PANELPOOLPLAYER_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT PanelPoolPlayer
#define UI_COMP_PANELPOOLPLAYER_PANELPOOLPLAYER 0
#define UI_COMP_PANELPOOLPLAYER_LABELPOOLPLYSCORE 1
#define UI_COMP_PANELPOOLPLAYER_LABELPOOLPLYCHANGE 2
#define UI_COMP_PANELPOOLPLAYER_LABELPOOLPLYNAME 3
#define UI_COMP_PANELPOOLPLAYER_PANELPOOLPLYSCORE 4
#define UI_COMP_PANELPOOLPLAYER_PANELPOOLPLYSCORE_LABELPLUS 5
#define UI_COMP_PANELPOOLPLAYER_PANELPOOLPLYSCORE_LABELMINUS 6
#define _UI_COMP_PANELPOOLPLAYER_NUM 7
lv_obj_t * ui_PanelPoolPlayer_create(lv_obj_t * comp_parent);
void ui_event_comp_PanelPoolPlayer_PanelPoolPlayer(lv_event_t * e);
void ui_event_comp_PanelPoolPlayer_LabelPlus(lv_event_t * e);
void ui_event_comp_PanelPoolPlayer_LabelMinus(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
