// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Settings

#include "../ui.h"

void ui_ScreenRestore_screen_init(void)
{
    ui_ScreenRestore = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenRestore, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ScreenRestore, &ui_img_snooker_table_480x320_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScreenRestore, &ui_font_UbuntuCyrillic25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RLabelQuestion = lv_label_create(ui_ScreenRestore);
    lv_obj_set_width(ui_RLabelQuestion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RLabelQuestion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RLabelQuestion, -2);
    lv_obj_set_y(ui_RLabelQuestion, -47);
    lv_obj_set_align(ui_RLabelQuestion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RLabelQuestion, "Восстановить счёт?");
    lv_obj_set_style_text_color(ui_RLabelQuestion, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RLabelQuestion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RLabelWait = lv_label_create(ui_ScreenRestore);
    lv_obj_set_width(ui_RLabelWait, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RLabelWait, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RLabelWait, -100);
    lv_obj_set_y(ui_RLabelWait, 50);
    lv_obj_set_align(ui_RLabelWait, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RLabelWait, "Ожидайте....");
    lv_obj_set_style_text_color(ui_RLabelWait, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RLabelWait, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RButtonYes = lv_btn_create(ui_ScreenRestore);
    lv_obj_set_height(ui_RButtonYes, 50);
    lv_obj_set_width(ui_RButtonYes, lv_pct(40));
    lv_obj_set_x(ui_RButtonYes, 40);
    lv_obj_set_y(ui_RButtonYes, 50);
    lv_obj_set_align(ui_RButtonYes, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_RButtonYes, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RButtonYes, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RButtonYes, lv_color_hex(0x0B4105), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RButtonYes, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RLabelYes = lv_label_create(ui_RButtonYes);
    lv_obj_set_width(ui_RLabelYes, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RLabelYes, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RLabelYes, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RLabelYes, "Да");

    ui_RButtonCancel = lv_btn_create(ui_ScreenRestore);
    lv_obj_set_height(ui_RButtonCancel, 50);
    lv_obj_set_width(ui_RButtonCancel, lv_pct(40));
    lv_obj_set_x(ui_RButtonCancel, -40);
    lv_obj_set_y(ui_RButtonCancel, 50);
    lv_obj_set_align(ui_RButtonCancel, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_RButtonCancel, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RButtonCancel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RButtonCancel, lv_color_hex(0x0B4105), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RButtonCancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RLabelCancel = lv_label_create(ui_RButtonCancel);
    lv_obj_set_width(ui_RLabelCancel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RLabelCancel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RLabelCancel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RLabelCancel, "Отмена");

    lv_obj_add_event_cb(ui_RButtonYes, ui_event_RButtonYes, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RButtonCancel, ui_event_RButtonCancel, LV_EVENT_ALL, NULL);

}
