#ifndef _UI_COMP_PANELPOOLPLAYER_H
#define _UI_COMP_PANELPOOLPLAYER_H

#ifdef __cplusplus
extern "C" {
#endif

#include "ui.h"

#define UI_COMP_PANELPOOLPLAYER_PANELPOOLPLAYER 0
#define UI_COMP_PANELPOOLPLAYER_LABELPOOLPLYSCORE 1
#define UI_COMP_PANELPOOLPLAYER_LABELPOOLPLYCHANGE 2
#define UI_COMP_PANELPOOLPLAYER_LABELPOOLPLYNAME 3
#define UI_COMP_PANELPOOLPLAYER_PANELPOOLPLYSCORE 4
#define UI_COMP_PANELPOOLPLAYER_PANELPOOLPLYSCORE_LABELPLUS 5
#define UI_COMP_PANELPOOLPLAYER_PANELPOOLPLYSCORE_LABELMINUS 6
#define _UI_COMP_PANELPOOLPLAYER_NUM 7

lv_obj_t * ui_PanelPoolPlayer_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
