// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Snooker

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenSnooker
void ui_ScreenSnooker_screen_init(void);
lv_obj_t * ui_ScreenSnooker;
lv_obj_t * ui_NLabelHome;
lv_obj_t * ui_NLabelRefresh;
lv_obj_t * ui_NRestYellow;
lv_obj_t * ui_NRestGreen;
lv_obj_t * ui_NRestBrown;
lv_obj_t * ui_NRestBlue;
lv_obj_t * ui_NRestPink;
lv_obj_t * ui_NRestBlack;
lv_obj_t * ui_NRestRed;
lv_obj_t * ui_NLabelRestRed;
lv_obj_t * ui_NLabelRestScore;
lv_obj_t * ui_NPanelPly1;
lv_obj_t * ui_NPlyLabelName1;
lv_obj_t * ui_NPlyLabelScore1;
lv_obj_t * ui_NPlyLabelMaxScore1;
lv_obj_t * ui_NPlyLabelDiff1;
lv_obj_t * ui_NPanelPlyBreak;
lv_obj_t * ui_NLabelPlyBreak;
lv_obj_t * ui_NPanelPly2;
lv_obj_t * ui_NPlyLabelName2;
lv_obj_t * ui_NPlyLabelScore2;
lv_obj_t * ui_NPlyLabelMaxScore2;
lv_obj_t * ui_NPlyLabelDiff2;
lv_obj_t * ui_NButtonCancel;
lv_obj_t * ui_NLabelCancel;
lv_obj_t * ui_BPanelBalls;
lv_obj_t * ui_BButtonRed;
lv_obj_t * ui_BLabel1;
lv_obj_t * ui_BButtonBlack;
lv_obj_t * ui_BLabel7;
lv_obj_t * ui_BButtonPink;
lv_obj_t * ui_BLabel6;
lv_obj_t * ui_BButtonBlue;
lv_obj_t * ui_BLabel5;
lv_obj_t * ui_BButtonBrown;
lv_obj_t * ui_BLabel4;
lv_obj_t * ui_BButtonGreen;
lv_obj_t * ui_BLabel3;
lv_obj_t * ui_BButtonYellow;
lv_obj_t * ui_BLabel2;
lv_obj_t * ui_BButtonMiss;
lv_obj_t * ui_BLabel0;
void ui_event_BButtonFoul(lv_event_t * e);
lv_obj_t * ui_BButtonFoul;
lv_obj_t * ui_BLabelFoul;
void ui_event_BButtonFreeBall(lv_event_t * e);
lv_obj_t * ui_BButtonFreeBall;
lv_obj_t * ui_BLabelFreeBall;
void ui_event_BButtonCancel(lv_event_t * e);
lv_obj_t * ui_BButtonCancel;
lv_obj_t * ui_BLabelCancel;
lv_obj_t * ui_BPanelFree;
lv_obj_t * ui_BButtonRedF;
lv_obj_t * ui_BLabelFB1;
lv_obj_t * ui_BButtonYellowF;
lv_obj_t * ui_BLabelFB2;
lv_obj_t * ui_BButtonGreenF;
lv_obj_t * ui_BLabelFB3;
lv_obj_t * ui_BButtonBrownF;
lv_obj_t * ui_BLabelFB4;
lv_obj_t * ui_BButtonBlueF;
lv_obj_t * ui_BLabelFB5;
lv_obj_t * ui_BButtonPinkF;
lv_obj_t * ui_BLabelFB6;
lv_obj_t * ui_BPanelFoul;
lv_obj_t * ui_BButtonF4;
lv_obj_t * ui_BLabelF4;
lv_obj_t * ui_BButtonF5;
lv_obj_t * ui_BLabelF5;
lv_obj_t * ui_BButtonF6;
lv_obj_t * ui_BLabelF6;
lv_obj_t * ui_BButtonF7;
lv_obj_t * ui_BLabelF7;
lv_obj_t * ui_BButtonF1;
lv_obj_t * ui_BLabelF1;
lv_obj_t * ui_MBPanelSnookerReset;
lv_obj_t * ui_MBLabelSnookerResetQ;
lv_obj_t * ui_MBBtnSnookerResetYes;
lv_obj_t * ui_MBLabelSnookerResetYes;
lv_obj_t * ui_MBBtnSnookerResetNo;
lv_obj_t * ui_MBLabelSnookerResetNo;
lv_obj_t * ui_MBPanelSnookerYellow;
lv_obj_t * ui_MBLabelSnookerYellowQ;
lv_obj_t * ui_MBBtnSnookerYellowYes;
lv_obj_t * ui_MBLabelSnookerYellowYes;
lv_obj_t * ui_MBBtnSnookerYellowNo;
lv_obj_t * ui_MBLabelSnookerYellowNo;
lv_obj_t * ui_NameKeyboard;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_snooker_table_480x[1] = {&ui_img_snooker_table_480x320_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_BButtonFoul(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_BPanelFoul, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_BPanelFree, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_BButtonFreeBall(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_BPanelFree, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_BPanelFoul, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_BButtonCancel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_BPanelFree, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_BPanelFoul, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenSnooker_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenSnooker);
}
