// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Lottery

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenLottery
void ui_ScreenLottery_screen_init(void);
lv_obj_t * ui_ScreenLottery;
lv_obj_t * ui_LLabelHome;
lv_obj_t * ui_LLabelRefresh;
lv_obj_t * ui_LRollerLots;
lv_obj_t * ui_LPanelLot;
lv_obj_t * ui_LLabelLot;
lv_obj_t * ui_LPanelLottery;
lv_obj_t * ui_LLabelLottery;
lv_obj_t * ui_LPanelListLots;
lv_obj_t * ui_LLabelListLots;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_snooker_table_480x[1] = {&ui_img_snooker_table_480x320_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenLottery_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenLottery);
}
