// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Lottery

#ifndef _SQUARELINE_LOTTERY_UI_H
#define _SQUARELINE_LOTTERY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_ScreenLottery
void ui_ScreenLottery_screen_init(void);
extern lv_obj_t * ui_ScreenLottery;
extern lv_obj_t * ui_LLabelHome;
extern lv_obj_t * ui_LLabelRefresh;
extern lv_obj_t * ui_LRollerLots;
extern lv_obj_t * ui_LPanelLot;
extern lv_obj_t * ui_LLabelLot;
extern lv_obj_t * ui_LPanelLottery;
extern lv_obj_t * ui_LLabelLottery;
extern lv_obj_t * ui_LPanelListLots;
extern lv_obj_t * ui_LLabelListLots;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_snooker_table_480x320_png);    // assets/snooker_table_480x320.png



LV_FONT_DECLARE(ui_font_UbuntuCyrillic25);
LV_FONT_DECLARE(ui_font_UbuntuDigits92);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
