// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Stream

#include "../ui.h"

void ui_comp_NameKeyboard_create_hook(lv_obj_t * comp)
{
}

void ui_comp_ScoreKeyboard_create_hook(lv_obj_t * comp)
{
}
