// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Darts

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenDarts
void ui_ScreenDarts_screen_init(void);
lv_obj_t * ui_ScreenDarts;
lv_obj_t * ui_DPanelPlayers;
void ui_event_DPanelPly1(lv_event_t * e);
lv_obj_t * ui_DPanelPly1;
lv_obj_t * ui_DLabelPly1;
void ui_event_DPanelPly2(lv_event_t * e);
lv_obj_t * ui_DPanelPly2;
lv_obj_t * ui_DLabelPly2;
void ui_event_DPanelPly3(lv_event_t * e);
lv_obj_t * ui_DPanelPly3;
lv_obj_t * ui_DLabelPly3;
lv_obj_t * ui_DPanelGame;
lv_obj_t * ui_DLabelSuggest;
void ui_event_DLabelScore(lv_event_t * e);
lv_obj_t * ui_DLabelScore;
lv_obj_t * ui_DPanelHistory;
lv_obj_t * ui_DLabelHistory;
void ui_event_DButtonSector(lv_event_t * e);
lv_obj_t * ui_DButtonSector;
lv_obj_t * ui_DLabelSector;
void ui_event_DButtonDouble(lv_event_t * e);
lv_obj_t * ui_DButtonDouble;
lv_obj_t * ui_DLabelDouble;
void ui_event_DButtonTriple(lv_event_t * e);
lv_obj_t * ui_DButtonTriple;
lv_obj_t * ui_DLabelTriple;
lv_obj_t * ui_DLabelHome;
void ui_event_DLabelReset(lv_event_t * e);
lv_obj_t * ui_DLabelReset;
lv_obj_t * ui_DLabelTrash;
lv_obj_t * ui_DPanelReset;
lv_obj_t * ui_DLabelNew;
void ui_event_DButtonYes(lv_event_t * e);
lv_obj_t * ui_DButtonYes;
lv_obj_t * ui_DLabelYes;
void ui_event_DButtonNo(lv_event_t * e);
lv_obj_t * ui_DButtonNo;
lv_obj_t * ui_DLabelNo;
lv_obj_t * ui_DPanelRemove;
lv_obj_t * ui_DLabelRemove;
void ui_event_DButtonRemoveYes(lv_event_t * e);
lv_obj_t * ui_DButtonRemoveYes;
lv_obj_t * ui_DLabelRemoveYes;
void ui_event_DButtonRemoveNo(lv_event_t * e);
lv_obj_t * ui_DButtonRemoveNo;
lv_obj_t * ui_DLabelRemoveNo;
lv_obj_t * ui_DPanelKB;
void ui_event_DTextArea(lv_event_t * e);
lv_obj_t * ui_DTextArea;
lv_obj_t * ui_DKeyboard;
lv_obj_t * ui_NameKeyboard;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_snooker_table_480x[1] = {&ui_img_snooker_table_480x320_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_DPanelPly1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_DPanelPly3, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_DPanelPly2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_DPanelPly1, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
}
void ui_event_DPanelPly2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_DPanelPly3, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_DPanelPly2, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_DPanelPly1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}
void ui_event_DPanelPly3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_DPanelPly3, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_DPanelPly2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_DPanelPly1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}
void ui_event_DLabelScore(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_DPanelKB, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_DButtonSector(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_DPanelKB, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_DButtonDouble(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_DPanelKB, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_DButtonTriple(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_DPanelKB, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_DLabelReset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_DPanelReset, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_DButtonYes(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_DPanelReset, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_DButtonNo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_DPanelReset, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_DButtonRemoveYes(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_DPanelRemove, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_DButtonRemoveNo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_DPanelRemove, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_DTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_DPanelKB, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenDarts_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenDarts);
}
