// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Darts

#ifndef _SQUARELINE_DARTS_UI_H
#define _SQUARELINE_DARTS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_ScreenDarts
void ui_ScreenDarts_screen_init(void);
extern lv_obj_t * ui_ScreenDarts;
extern lv_obj_t * ui_DPanelPlayers;
void ui_event_DPanelPly1(lv_event_t * e);
extern lv_obj_t * ui_DPanelPly1;
extern lv_obj_t * ui_DLabelPly1;
void ui_event_DPanelPly2(lv_event_t * e);
extern lv_obj_t * ui_DPanelPly2;
extern lv_obj_t * ui_DLabelPly2;
void ui_event_DPanelPly3(lv_event_t * e);
extern lv_obj_t * ui_DPanelPly3;
extern lv_obj_t * ui_DLabelPly3;
extern lv_obj_t * ui_DPanelGame;
extern lv_obj_t * ui_DLabelSuggest;
void ui_event_DLabelScore(lv_event_t * e);
extern lv_obj_t * ui_DLabelScore;
extern lv_obj_t * ui_DPanelHistory;
extern lv_obj_t * ui_DLabelHistory;
void ui_event_DButtonSector(lv_event_t * e);
extern lv_obj_t * ui_DButtonSector;
extern lv_obj_t * ui_DLabelSector;
void ui_event_DButtonDouble(lv_event_t * e);
extern lv_obj_t * ui_DButtonDouble;
extern lv_obj_t * ui_DLabelDouble;
void ui_event_DButtonTriple(lv_event_t * e);
extern lv_obj_t * ui_DButtonTriple;
extern lv_obj_t * ui_DLabelTriple;
extern lv_obj_t * ui_DLabelHome;
void ui_event_DLabelReset(lv_event_t * e);
extern lv_obj_t * ui_DLabelReset;
extern lv_obj_t * ui_DLabelTrash;
extern lv_obj_t * ui_DPanelReset;
extern lv_obj_t * ui_DLabelNew;
void ui_event_DButtonYes(lv_event_t * e);
extern lv_obj_t * ui_DButtonYes;
extern lv_obj_t * ui_DLabelYes;
void ui_event_DButtonNo(lv_event_t * e);
extern lv_obj_t * ui_DButtonNo;
extern lv_obj_t * ui_DLabelNo;
extern lv_obj_t * ui_DPanelRemove;
extern lv_obj_t * ui_DLabelRemove;
void ui_event_DButtonRemoveYes(lv_event_t * e);
extern lv_obj_t * ui_DButtonRemoveYes;
extern lv_obj_t * ui_DLabelRemoveYes;
void ui_event_DButtonRemoveNo(lv_event_t * e);
extern lv_obj_t * ui_DButtonRemoveNo;
extern lv_obj_t * ui_DLabelRemoveNo;
extern lv_obj_t * ui_DPanelKB;
void ui_event_DTextArea(lv_event_t * e);
extern lv_obj_t * ui_DTextArea;
extern lv_obj_t * ui_DKeyboard;
extern lv_obj_t * ui_NameKeyboard;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_snooker_table_480x320_png);    // assets/snooker_table_480x320.png



LV_FONT_DECLARE(ui_font_UbuntuCyrillic25);
LV_FONT_DECLARE(ui_font_UbuntuDigits92);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
