// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Snooker

#ifndef _UI_COMP_NAMEKEYBOARD_H
#define _UI_COMP_NAMEKEYBOARD_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT NameKeyboard
#define UI_COMP_NAMEKEYBOARD_NAMEKEYBOARD 0
#define UI_COMP_NAMEKEYBOARD_NAMELIST 1
#define UI_COMP_NAMEKEYBOARD_NAMETEXTAREA 2
#define UI_COMP_NAMEKEYBOARD_BUTTONCLOSE 3
#define UI_COMP_NAMEKEYBOARD_BUTTONCLOSE_LABELCLOSE 4
#define UI_COMP_NAMEKEYBOARD_KEYBOARDBUTTONS 5
#define _UI_COMP_NAMEKEYBOARD_NUM 6
lv_obj_t * ui_NameKeyboard_create(lv_obj_t * comp_parent);
void ui_event_comp_NameKeyboard_NameKeyboard(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
